### ISSUE TITLE
Missing location and population data for FRA provinces

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#102]
There are a few missing regions, and some problematic ones that break FRA itself:

  ⚠️  Skipping MTQ because it breaks France
  ⚠️  Skipping REU because it breaks France
  ❌ Could not find location French Polynesia, FRA
  ⚠️  Skipping GUF because it breaks France
  ❌ Could not find location Saint-Barthélemy, FRA
  ❌ Could not find location Saint-Martin, FRA
  ❌ Could not find location Guyane, FRA
  ❌ Could not find location Ile-de-France, FRA
  ❌ Could not find location Centre-Val de Loire, FRA
  ❌ Could not find location Bourgogne-Franche-Comté, FRA
  ❌ Could not find location Normandie, FRA
  ❌ Could not find location Hauts-de-France, FRA
  ❌ Could not find location Grand Est, FRA
  ❌ Could not find location Nouvelle-Aquitaine, FRA
  ❌ Could not find location Occitanie, FRA
  ❌ Could not find location Auvergne-Rhône-Alpes, FRA
  ❌ Could not find location Provence-Alpes-Côte d’Azur, FRA

And we're missing population data for tons too:

  ❌ Saint-Barthélemy, FRA: ?
  ❌ Saint-Martin, FRA: ?
  ❌ Guadeloupe, FRA: ?
  ❌ Martinique, FRA: ?
  ❌ Guyane, FRA: ?
  ❌ La Réunion, FRA: ?
  ❌ Mayotte, FRA: ?
  ❌ Ile-de-France, FRA: ?
  ❌ Centre-Val de Loire, FRA: ?
  ❌ Bourgogne-Franche-Comté, FRA: ?
  ❌ Normandie, FRA: ?
  ❌ Hauts-de-France, FRA: ?
  ❌ Grand Est, FRA: ?
  ❌ Pays de la Loire, FRA: ?
  ❌ Bretagne, FRA: ?
  ❌ Nouvelle-Aquitaine, FRA: ?
  ❌ Occitanie, FRA: ?
  ❌ Auvergne-Rhône-Alpes, FRA: ?
  ❌ Provence-Alpes-Côte d’Azur, FRA: ?
  ❌ Corse, FRA: ?

**Comment by JiPiBi** [comment]
Data for France  from 1/1/2020  : Can help ? 

Auvergne-Rhône-Alpes | 8 032   377
-- | --
Bourgogne-Franche-Comté | 2 783 039
Bretagne | 3 340 379
Centre-Val-de-Loire | 2 559 073
Corse | 344 679
Grand Est | 5 511 747
Hauts-de-France | 5 962 662
Île-de-France | 12 278   210
Normandie | 3 303 500
Nouvelle-Aquitaine | 5 999 982
Occitanie | 5 924 858
Pays de la   Loire | 3 801 797
Provence-Alpes-Côte   d'Azur | 5 055 651
France métropolitaine | 64 897 954
Guadeloupe | 376 879
Martinique | 358 749
Guyane | 290 691
La Réunion | 859 959
Mayotte | 279 471
DOM | 2 165 749
France   métropolitaine et DOM | 67 063   703

Seems that your data for France in on the map  are quite wrong : France is all green !
Official values  today 19/03 



Date | Province | State | Cases | Reanimation | Hospitalise | Death | Tested | Recovered
-- | -- | -- | -- | -- | -- | -- | -- | --
19/03/2020 | Auvergne-Rhône-Alpes | France | 1014 |   |   |   |   |  
19/03/2020 | Bourgogne-Franche-Comté | France | 696 |   |   |   |   |  
19/03/2020 | Bretagne | France | 297 |   |   |   |   |  
19/03/2020 | Centre-Val de Loire | France | 157 |   |   |   |   |  
19/03/2020 | Corse | France | 162 |   |   |   |   |  
19/03/2020 | Grand Est | France | 2643 |   |   |   |   |  
19/03/2020 | Hauts-de-France | France | 700 |   |   |   |   |  
19/03/2020 | Ile-de-France | France | 3384 |   |   |   |   |  
19/03/2020 | Normandie | France | 241 |   |   |   |   |  
19/03/2020 | Nouvelle-Aquitaine | France | 280 |   |   |   |   |  
19/03/2020 | Occitanie | France | 444 |   |   |   |   |  
19/03/2020 | Pays de la Loire | France | 160 |   |   |   |   |  
19/03/2020 | Provence-Alpes-Côte d’Azur | France | 693 |   |   |   |   |  
19/03/2020 | Guadeloupe | France | 45 |   |   |   |   |  
19/03/2020 | Saint-Barthélémy | France | 3 |   |   |   |   |  
19/03/2020 | Saint-Martin | France | 4 |   |   |   |   |  
19/03/2020 | Guyane | France | 15 |   |   |   |   |  
19/03/2020 | Martinique | France | 32 |   |   |   |   |  
19/03/2020 | Mayotte | France | 6 |   |   |   |   |  
19/03/2020 | La Réunion | France | 19 |   |   |   |   |  
19/03/2020 | France | France | 10995 | 1122 | 3339 | 372 |   | 1300

**Comment by claustres** [comment]
As far as I can see the mapping data https://github.com/lazd/coronavirus-data-sources/tree/0fde87fc468d8e9ac820f99223a6053e6e0e573f/geojson used are at the departmental level while the numbers your are talking about and the data processed by the scrapper are at the regional level. A region in France contains many departments.

Should we change the scrapper to process data at the departmental level ? This can be a problem because the main data are only available at the regional level in France.

Otherwise how could we update the mapping data ? A good source could be https://github.com/gregoiredavid/france-geojson, file `regions-avec-outre-mer.geojson`.

Last but not least how is the mapping performed ? If by name this can also be a problem because in French names contains hyphen or accents that are not always written similarly in different sources. Does it helps if the scrapper provide lat/long ?

Thanks for feedback.

**Comment by liszto** [comment]
The data are available at a departmental level in the scrapper's source. OR maybe I missed something ? 🤔 so I think it could be easy to edit the scrapper to parse them instead of region.

**Comment by qgolsteyn** [comment]
Data is available at the departmental level yes. We decided to start with régions first as they are the highest-level regional level (comparable to states in the USA). Department would probably be counties in the dataset (not the best term however).

There is no explicit mapping data for France right now. As @claustres mentioned, I think our best bet would be to go for https://github.com/gregoiredavid/france-geojson. Mapping is performed by name matching right now, which is clearly not the best approach. We are looking at moving mapping matching to each scrapper, to allow for each scrapper to come up with the best solution for each country/state.

Adding #167 to track moving mapping to each scrapper. Adding mapping to French region should be trivial once this change is made.

**Comment by JiPiBi** [comment]
this link perhaps could help to get the link between departments and regions
https://fr.wikipedia.org/wiki/Liste_des_d%C3%A9partements_fran%C3%A7ais
in the chapter : Liste des départements


I seems to me that the region values are more reliable , I read a bit the departemental level with pandas , and I see much NaN

**Comment by claustres** [comment]
@liszto No the current scrapper works at region level. The problem is that data for departments is not yet reliable and has a lot of holes so best bet is region now. 

Moving mapping matching to each scrapper seems to me the right way to go, just as each scrapper is responsible of its own data part in the global dataset. The scrapper might simply return a GeoJson geometry (point or polygon). As mentioned matching by name is usually a bad idea due to linguistic features, for instance in France we use dedicated code for region and departments.

**Comment by claustres** [comment]
If you'd like to have an idea we publish GeoJson with the data here https://github.com/kalisio/covid-19.

**Comment by qgolsteyn** [comment]
Population and features are now available.
