### ISSUE TITLE
State totals should be calculated if state's website shows all counties

### ISSUE THREAD

**Issue by ssljivar** [lazd/coronadatascraper#15]
When available, the County-level data for the US is provided in addition to the State-level data, causing duplication.  For example, New Jersey state-level data shows 29 cases (County == NULL), and County-level data aggregates to 47 cases.  Suggest to exclude the State-level data when County-level data is available.  

Also, State descriptors for State-level and County-level data is inconsistent.  For example, "New Jersey" and "NJ" (see https://github.com/lazd/coronadatascraper/issues/16)

Finally, suggestion to use "(unknown)" literal value for Counties when either data is available only at the State (or Country) level.

**Comment by lazd** [comment]
Thanks for the report, it got me thinking...

For the most part, it is intended that we provide both county and state-level data, even if duplicative. Unlike the JHU dataset, we cite both county and state. It's up to you to work with the data at the level of granularity you need for your application. If you want state level data, ignore anything that has a `city` or `county` field and just use those that have `state` only. That said, it will be hard to calculate a "total number of cases" because you don't know precisely what to sum...

Note that, just because we have county data, doesn't mean it's complete -- for California, for instance, we have to manually get county data on a per-county basis, so the CDC total for California may be more accurate than summing our counties.

As far as differences in totals, note that the state data is coming from the CDC (and is often given as a range), and they may be slow to update.

HOWEVER, you're right that, for states we can scrape all of the counties together, it we should update the total for the state data, ignoring whatever comes from CDC... I will investigate updating state data when all counties are present as part of this issue.

Re: `(unknown)`, I'd rather not use a literal string, that will result in a special case in everyone's parser.

You are right about `state` fields being inconsistent, I've filed https://github.com/lazd/coronadatascraper/issues/16 to fix this.

Luckily, I'm caching all of the data. I'll be able to re-generate previous days if we change things like normalizing `state` values and summing county data.

**Comment by JimBudde** [comment]
I am hoping a simpler solution might involve the following logic given the reporting time differences already noted by county, state, or cdc.  
If State (Parent) number is higher than sum of counties (children), then calculate difference and allocate to "Undisclosed" (or similarly named) 'county' record.  If the State number is lower than sum of counties, then replace the state total with sum of counties.  The numbers will never be spot-on, but *think* this logic makes the most sense at the moment.
I am fine with keeping the state and county numbers together which some will say results in "double-counting" when rolling up values, but this is a data analysis issue, not a data recording issue.  It just needs to be consistent logic so either all parents show their children's total, or none do.  
Awesome work btw!

**Comment by lazd** [comment]
@JimBudde that's very clever, we should implement that! Right now, we just roll up state data and only have `(unassigned)` if the state provides data for unassigned counties.

Yes, people will say "double-counting," and we'll say "work with the data at the granularity level you need it, and always add salt."

Thanks!

**Comment by lazd** [comment]
All scrapers that get county-level data sum it up nicely now. We don't run the equation that @JimBudde came up with, but I'm going to consider this close for now.

We using `(unassigned)` for situation where a state reports data, but doesn't tell us what county its in, so that's handled.

Note that we are still including state data if county data is present. It's up to users to filter for the granularity they want. Unfortunately, that makes summing the data difficult, we'll have to add a routine to perform the "dedupe" and sum properly. I've filed #100 to track that.

Thanks!
