### ISSUE TITLE
Delaware, USA only has three counties

### ISSUE THREAD

**Issue by ktice** [lazd/coronadatascraper#195]
The current data lists 6.   The correct counties are New Castle, Kent, and Sussex.  Nice work on this btw!

**Comment by lazd** [comment]
Ok, it looks like the scraper is getting additional information from Delaware, likely a combined county situation due to hospitals being shared. This data shouldn't be hurting anything, but it might mess with the totals of Delaware itself...

Can you shed some light on what the other 3 "counties" are supposed to represent?

**Comment by veyEskelson** [comment]
Pea Patch island- in New Castle County
Reedy island - in New Castle County
DE/NJ- Likely represents Metropolitan/Micropolitan Area or Combined Statistical Area.

**Comment by lazd** [comment]
Ok, do you think the data for New Castle County already includes Pea Patch and Reedy Island? If so, we can discard it. We can likely discard the DE/NJ data too, yes?
