### ISSUE TITLE
negative counts in timeseries.csv

### ISSUE THREAD

**Issue by tautme** [lazd/coronadatascraper#354]
![image](https://user-images.githubusercontent.com/15580867/77587298-a08db980-6eb5-11ea-8c95-47e9e5284969.png)

There is also 0.5 counts for type active and cases (https://github.com/lazd/coronadatascraper/issues/356)

<img width="928" alt="image" src="https://user-images.githubusercontent.com/15580867/77587664-5ce77f80-6eb6-11ea-81a9-e53653984e19.png">

**Comment by lazd** [comment]
I know exactly why the Utah problem was happening, that can be fixed easily (they're reporting 3 counties as "Tri-county").

For CHE, maybe they switched to offer daily data instead of cumulative... They switched the data source up before and broke everything, so I wouldn't put it past them.
 
@qgolsteyn can you investigate CHE? I can fixup Utah.

**Comment by lazd** [comment]
@tautme fixed the Utah issues, filed separate issue https://github.com/lazd/coronadatascraper/issues/356

**Comment by lazd** [comment]
@qgolsteyn I think this is an issue with the source -- even if there was something weird, they have `deaths` and `recovered` > `cases`.

**Comment by qgolsteyn** [comment]
The source appears to have missing entries for cases, which would make active negative if deaths are reported

**Comment by qgolsteyn** [comment]
See #357 for decision on active. Closed with 84e8a277
