### ISSUE TITLE
California Data URLs give different results

### ISSUE THREAD

**Issue by firebuggirl** [lazd/coronadatascraper#415]
Hi all,

When I run `yarn start` locally I am noticing that the numbers for cases/deaths (etc.,) being projected to the `dist/` directory in many California counties differ from the numbers that are being displayed via many of the individual urls that are used in each individual scraper.

For example, if I simply run `yarn start`,  the resulting output for the county of Los Angeles states that there are currently 814 cases in the county of Los Angeles (@8pm PST - 3/26). But, if I comment out `src/events/crawler/scrapers/USA/CA/index.js` completely the number of cases returned is `1216`, which directly (correctly?) matches what is being displayed on the L.A. County (http://www.publichealth.lacounty.gov/media/Coronavirus/) website. So there appears to be a lag in reporting/updating the data via the data source `https://docs.google.com/spreadsheets/d/1CwZA4RPNf_hUrwzNLyGGNHRlh1cwl8vDHwIoae51Hac/gviz/tq?tqx=out:csv&sheet=master` being queried via `src/events/crawler/scrapers/USA/CA/index.js` as compared to the urls provided in many/some of the individual scrapers in CA.

Is there an alternative way to get the data for California that is closer to real time than what is being defaulted to via  the csv speadsheet?

This is an incredible project btw! 

Cheers:-)

**Comment by lazd** [comment]
It looks like @HarrietRowan was a little slow to update the spreadsheet today, but it's showing 1230 now.

**Comment by HarrietRowan** [comment]
I think that was a timing issue, 814 was the total at EOD on the 25th. But the numbers in my spreadsheet is usually slightly different (higher) than what they display on the website because I have a colleague down there who is getting timely reports from the three public health departments that are added together to come up with the LA county total, so we have slightly more up-to-date numbers than the public health dept website.

**Comment by firebuggirl** [comment]
Hi @lazd  & @HarrietRowan ,

I see...was just curious.. Thanks to you both for all of your hard work!
